baijie/urls.py
# -*- coding: utf-8 -*-
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name="home"),
    url(r'(?P<article_id>\d+)/$', views.BaijieDetailView.as_view(), name="blog_detail"),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^movie/$', views.MovieView.as_view(), name='movie'),
    url(r'^about/$', views.aboutview, name='about'),
    url(r'^play/(?P<pk>\d+)$', views.MoviePlay.as_view(), name='play'),
]

blog/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from . import views


urlpatterns = [
    # IndexView 是一个类，不能直接替代 index 函数。这里调用的是as_view（）方法，将一个类转换成一个函数
    url(r'^$', views.IndexView.as_view(), name="index"),

    # （?P<article_id>\d）的作用是从用户访问的URL里把匹配的字符串捕获并作为关键字参数传给对应的视图函数article_detail
    url(r'^article/(?P<article_id>\d+)/$', views.BlogDetailView.as_view(), name="blog_detail"),
    url(r'^about/$', views.AboutView.as_view(), name='about'),
    url(r'^category/([\w\s]+)/$', views.CategoryDetail.as_view(), name='category'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'^baijie/', include('baijie.urls', namespace='baijie', app_name='baijie')),
    url(r'^search/', include('haystack.urls')),
]

baijie/models.py
# -*- coding: utf-8 -*-

import markdown
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.utils.html import strip_tags


class BaiJie(models.Model):
    title = models.CharField(max_length=60)
    author = models.ForeignKey(User, related_name='blog_baijie')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    excerpt = models.CharField(max_length=125, blank=True)
    views = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ("-publish",)

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    def save(self, *args, **kwargs):
        if not self.excerpt:
            md = markdown.Markdown(extensions=['markdown.extensions.extra', ])
            self.excerpt = strip_tags(md.convert(self.body))[:90]
        super(BaiJie, self).save(*args, **kwargs)

    def __str__(self):
        return self.title


class Movie(models.Model):
    movie = models.CharField(max_length=90)
    movie_url = models.CharField(max_length=90)
    image_url = models.CharField(max_length=90)

    def __str__(self):
        return self.movie

# Create your models here.

baijie/forms.py
# -*- coding: utf-8 -*-
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

baijie/views.py
# -*- coding: utf-8 -*-

import markdown
from .models import BaiJie, Movie
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView


def aboutview(request):
    return render(request, 'baijie/about.html')


# 使用django 自带的装饰器函数，参数login_url= 将没有登录的用户转到自定义的登录界面
class MovieView(LoginRequiredMixin, ListView):
    # login_url 是绝对路径，即有斜杠的
    login_url = '/baijie/login/'
    redirect_field_name = 'next'
    model = Movie
    template_name = 'baijie/movie.html'
    context_object_name = "movie_list"
    paginate_by = 10


class MoviePlay(LoginRequiredMixin, DetailView):
    login_url = '/baijie/login/'
    redirect_field_name = 'next'
    model = Movie
    template_name = 'baijie/play.html'
    context_object_name = 'play'
    pk_url_kwarg = 'pk'


class HomeView(ListView):
    model = BaiJie
    template_name = 'baijie/home.html'
    context_object_name = 'baijies'
    paginate_by = 3


class BaijieDetailView(DetailView):
    model = BaiJie
    template_name = 'baijie/detail.html'
    context_object_name = 'article'
    pk_url_kwarg = 'article_id'

    def get(self, request, *args, **kwargs):
        response = super(BaijieDetailView, self).get(request, *args, **kwargs)
        self.object.increase_views()
        return response

    def get_object(self, queryset=None):
        obj = super(BaijieDetailView, self).get_object(queryset=None)
        # 有些扩展需要手动打开
        obj.body = markdown.markdown(obj.body, extensions=['markdown.extensions.extra', ])
        return obj

templates/baijie/about.html
{% extends 'basebaijie.html' %}

    {% block main %}
    <div style="text-align:center">
        <h2>
            《孤独》
        </h2>
        <br>
        <p>“从童年起，我便独自一人”</p>
        <br>
        <p>照顾着</p>
        <br>
        <p>历代的星辰</p>
    </div>
    {% endblock %}

templates/baijie/detail.html
{% extends 'basebaijie.html' %}

{% block main %}
    <article class="blog article-{{ article.id }}">
        <header class="entry-header">
            <h1 class="entry-title">
                {{ article.title }}
            </h1>
            <div class="entry-meta">
                <span class="post-category"><a href="#">{{ article.category }}</a></span>
                <span class="post-date"><a href="#"><time class="entry-date">{{ article.publish }}</time></a></span>
                <span class="views-count"><a href="#">{{ article.views }} 阅读</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            {{ article.body|safe }}
        </div>
    </article>
{% endblock main %}

templates/baijie/home.html
{% extends 'basebaijie.html' %}
{% block main %}
{% for baijie in baijies %}
<article class="blog blog-{{ baijie.id }}">
    <header class="entry-header">
        <h1 class="entry-title">
            <a href="{% url 'baijie:blog_detail' baijie.id %}">{{ baijie.title }}</a>
        </h1>
        <div class="entry-meta">
            <span class="post-date"><a href="javascript:void(0);"><time>{{ baijie.publish }}</time></a></span>
            <span class="views-count"><a href="javascript:void(0);">{{ baijie.views }} 阅读</a></span>
        </div>
    </header>
    <div class="entry-content clearfix">
        <p>{{ baijie.excerpt }}...</p>
        <div class="read-more cl-effect-14">
            <a href="{% url 'baijie:blog_detail' baijie.id %}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
        </div>
    </div>
</article>
{% empty %}
<div class="no-post">暂时还没有发布的文章！</div>
{% endfor %}
<br>
{% include 'paginator.html' %}
{% endblock main %}

templates/baijie/movie.html
{% extends 'basebaijie.html'%}
{% load staticfiles %}

{% block main %}
    <div class="pageContainer">
        <ul class="movieUl row">
             {% for movie in movie_list %}
            <li class="movieLi col-xs-12 col-sm-12 col-md-2" title="{{ movie.movie }}">
                <a class="movieHref" href="{% url 'baijie:play' movie.id %}">
                    <img class="movieImg" src="{% static movie.image_url %}">
                    <span class="movieName">{{ movie.movie }}</span>
                </a>
            </li>
             {% endfor %}
        </ul>
    </div>
    <br>
    {% include 'paginator.html' %}
{% endblock %}

templates/baijie/play.html
{% extends 'basebaijie.html' %}
{% load staticfiles %}
{% block main %}
    <div>
        <div class="moviePlayCon">
            <p class="moviePlayName">{{play.movie}}</p>
            <video class="moviePlayWindow" controls="controls">
                <source src="{% static play.movie_url %}" type="video/mp4">
                Your browser does not support the video tag.
            </video>
        </div>
    </div>
{% endblock %}