baijie/urls.py
# -*- coding: utf-8 -*-
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name="home"),
    url(r'(?P<article_id>\d+)/$', views.BaijieDetailView.as_view(), name="blog_detail"),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^movie/$', views.MovieView.as_view(), name='movie'),
    url(r'^about/$', views.aboutview, name='about'),
    url(r'^play/(?P<pk>\d+)$', views.MoviePlay.as_view(), name='play'),
]

blog/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from . import views


urlpatterns = [
    # IndexView 是一个类，不能直接替代 index 函数。这里调用的是as_view（）方法，将一个类转换成一个函数
    url(r'^$', views.IndexView.as_view(), name="index"),

    # （?P<article_id>\d）的作用是从用户访问的URL里把匹配的字符串捕获并作为关键字参数传给对应的视图函数article_detail
    url(r'^article/(?P<article_id>\d+)/$', views.BlogDetailView.as_view(), name="blog_detail"),
    url(r'^about/$', views.AboutView.as_view(), name='about'),
    url(r'^category/([\w\s]+)/$', views.CategoryDetail.as_view(), name='category'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'^baijie/', include('baijie.urls', namespace='baijie', app_name='baijie')),
    url(r'^search/', include('haystack.urls')),
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>我的猫呢</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="shortcut icon" href="{% static 'favicon.ico' %}">

    <style>
        span.highlighted {
            color: red;
        }
    </style>

    <!-- css -->

    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'css/highlights/github.css' %}">
    <link rel="stylesheet" href="{% static 'css/pagination.css' %}">

    <!-- js -->
    <script src="{% static 'js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/pace.min.js' %}"></script>
    <script src="{% static 'js/modernizr.custom.js' %}"></script>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <!-- 采用这种形式是为了避免硬编码，只要 url.py 中的 name=index 不变，
                    则路径的修改不影响这里的超链接.这里的 blog 是指模板 index.html 中的blog -->
                    <h1><a href="{% url 'blog:index' %}"><b>我的猫呢</b></a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="/blog" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="javascript:void(0);" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="{% url 'blog:about' %}" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="javascript:void(0);" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                    <!--‘form’中提供正确的参数如name="q"，method="get"以及你的action地址就OK了-->
                        <form role="search" method="get" id="searchform" action="{% url 'haystack_search' %}">
                            <input type="search" name="q" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block main %}
                {% endblock main %}
            </main>
            <aside class="col-md-4">
                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                        <ul>
                        {% for category in category_list %}
                        <li>
                            <a href="{% url 'blog:category' category.name %}">{{ category.name }} <span class="post-count">({{ category.get_blog_count }})</span></a>
                        </li>
                        {% empty %}
                        <i>hi, 你好啊</i>
                        {% endfor %}
                    </ul>
                </div>
                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    <ul>
                        <li>Django</li>
                        <li>Python</li>
                        <li>这里没有猫</li>
                    </ul>
                </div>
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2018 (纪念一只喵)</p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="/blog">首页</a></li>
            <li><a href="#">博客</a></li>
            <li><a href="{% url 'blog:about' %}">关于</a></li>
            <li><a href="#">联系</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'blog/js/script.js' %}"></script>

</body>
</html>

templates/basebaijie.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>少妇白洁</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="shortcut icon" href="{% static 'favicon.ico' %}">

    <style>
        span.highlighted {
            color: red;
        }
    </style>

    <!-- css -->

    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'css/highlights/github.css' %}">
    <link rel="stylesheet" href="{% static 'css/pagination.css' %}">
    <link rel="stylesheet" href="{% static 'css/movielist.css' %}">
    <link rel="stylesheet" href="{% static 'css/play.css' %}">

    <!-- js -->
    <script src="{% static 'js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/pace.min.js' %}"></script>
    <script src="{% static 'js/modernizr.custom.js' %}"></script>
</head>

	<body ondragstart="window.event.returnValue=false" oncontextmenu="window.event.returnValue=false" onselectstart="event.returnValue=false">
		<div class="container">
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="{% url 'baijie:home' %}">少妇白洁</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="{% url 'baijie:home' %}" data-hover="首页">首页</a></li>
    								<li class="cl-effect-11"><a href="{% url 'baijie:movie' %}" data-hover="视频">视频</a></li>
    								<li class="cl-effect-11"><a href="{% url 'baijie:about' %}" data-hover="关于">关于</a></li>
    								<li class="cl-effect-11"><a href="#" data-hover="联系">联系</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>
        <div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
                        {% block main %}
                        {% endblock %}
                    </main>
                </div>
            </div>
        </div>
        <footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy 第二快播の少妇白洁</p>
					</div>
				</div>
			</div>
		</footer>
        <!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="{% url 'baijie:home' %}">首页</a></li>
					<li><a href="{% url 'baijie:movie' %}">视频</a></li>
					<li><a href="{% url 'baijie:about' %}">关于</a></li>
					<li><a href="#">联系</a></li>
				</ul>
			</nav>
		</div>

		<script src="{% static 'blog/js/script.js' %}"></script>

	</body>
</html>

templates/paginator.html
<!-- ListView 传递了以下和分页有关的模板变量供我们在模板中使用：
    1.paginator ，即 Paginator 的实例。
    2.page_obj ，当前请求页面分页对象。
    3.is_paginated，是否已分页。只有当分页后页面超过两页时才算已分页。
    4.object_list，请求页面的对象列表，和 post_list 等价。所以在模板中循环文章列表时可以选 post_list ，也可以选 object_list。
-->

{% if is_paginated %}
<div class="center">
    <span class="pagination">
        {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
        {% endif %}
    </span>
    <span class="current">
        第 {{ page_obj.number }} 页 / 共 {{ paginator.num_pages }} 页
    </span>
    <span class="pagination">
        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">下一页</a>
        {% endif %}
    </span>
    <span class="pagination">
    <form action="" method="get">
        <td>&nbsp;到第</td>
        <td><input style="background-color:transparent; border-width:1;" name="page" type="text" size="2"></td>
        <td>页</td>
        <td><input style="background-color:transparent; border-width:1;" type="submit" value="跳转"></td>
    </form>
    </span>
</div>
{% endif %}

<!--
{% if is_paginated %}
<table class="noframe">
<tr>
{% if page_obj.has_previous %}
<td><a href="?page={{page_obj.previous_page_number}}">上一页</a></td>
{% endif %}
{% if page_obj.has_next %}
<td><a href="?page={{page_obj.next_page_number}}">下一页</a></td>
{% endif %}
<td>第{{page_obj.number}}页，共{{paginator.num_pages}}页</td>
<form action="" method="get">
<td>&nbsp;到第</td>
<td><input name="page" type="text" size="2"></td>
<td>页</td>
<td><input type="submit" value="跳转"></td>
</form>
</tr>
</table>
{% endif %}
-->